server: 
  port: 8110

info:
  name: AdminService

spring:
  application:
    name: AdminService
  boot:
    admin: 
      context-path: /admin   
  output:
    ansi:
      enabled: ALWAYS
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  path: logfile

security:
  basic:
    enabled: false
#   oauth2:
#     client:
#       clientId: proto
#       clientSecret: protoSecret
#       scope: proto
#       access-token-uri: http://localhost:9999/uaa/oauth/token
#       user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
#     resource:
#       user-info-uri: http://localhost:9999/uaa/me
